#!/bin/bash
# OperatorOne - Secret Generator
# Usage: ./generate-secrets.sh > .env
#
# This script generates all required secrets for a new deployment.
# Review the output before using in production.

set -e

# Function to generate random hex string
generate_hex() {
    local length=${1:-32}
    openssl rand -hex $length
}

# Function to generate random alphanumeric string
generate_alphanum() {
    local length=${1:-32}
    openssl rand -base64 $length | tr -dc 'a-zA-Z0-9' | head -c $length
}

# Function to generate bcrypt hash for htpasswd
generate_htpasswd() {
    local user=$1
    local pass=$2
    # Using openssl for compatibility
    echo -n "${user}:" && openssl passwd -apr1 "${pass}" | sed -e 's/\$/\$\$/g'
}

echo "# OperatorOne - Generated Environment"
echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "# WARNING: Store this file securely and never commit to git!"
echo ""

echo "# ==========================================="
echo "# DOMAIN CONFIGURATION"
echo "# ==========================================="
echo "DOMAIN=example.com  # CHANGE THIS"
echo "ACME_EMAIL=admin@example.com  # CHANGE THIS"
echo "TIMEZONE=America/Denver"
echo ""

echo "# ==========================================="
echo "# TRAEFIK DASHBOARD"
echo "# ==========================================="
TRAEFIK_PASS=$(generate_alphanum 16)
echo "# Dashboard password: ${TRAEFIK_PASS}"
echo "TRAEFIK_DASHBOARD_AUTH=$(generate_htpasswd admin "${TRAEFIK_PASS}")"
echo ""

echo "# ==========================================="
echo "# POSTGRESQL CREDENTIALS"
echo "# ==========================================="
echo "POSTGRES_ROOT_PASSWORD=$(generate_alphanum 32)"
echo "POSTGRES_OPENBAO_PASSWORD=$(generate_alphanum 32)"
echo "POSTGRES_N8N_PASSWORD=$(generate_alphanum 32)"
echo "POSTGRES_AUTHENTIK_PASSWORD=$(generate_alphanum 32)"
echo "POSTGRES_PORTAL_PASSWORD=$(generate_alphanum 32)"
echo ""

echo "# ==========================================="
echo "# OPENBAO SECRETS"
echo "# ==========================================="
echo "OPENBAO_UNSEAL_KEY=  # Generated by init-openbao.sh after first boot"
echo "OPENBAO_ROOT_TOKEN=  # Generated by init-openbao.sh after first boot"
echo "OPENBAO_SERVICE_TOKEN=  # Generated by init-openbao.sh after first boot"
echo ""

echo "# ==========================================="
echo "# N8N SECRETS"
echo "# ==========================================="
echo "N8N_ENCRYPTION_KEY=$(generate_alphanum 32)"
echo "N8N_JWT_SECRET=$(generate_alphanum 32)"
echo ""

echo "# ==========================================="
echo "# AUTHENTIK SECRETS"
echo "# ==========================================="
echo "AUTHENTIK_SECRET_KEY=$(generate_alphanum 50)"
AUTHENTIK_BOOT_PASS=$(generate_alphanum 24)
echo "# Bootstrap password (enter this in the setup wizard): ${AUTHENTIK_BOOT_PASS}"
echo "AUTHENTIK_BOOTSTRAP_PASSWORD=${AUTHENTIK_BOOT_PASS}"
echo "AUTHENTIK_BOOTSTRAP_TOKEN=$(generate_alphanum 48)"
echo ""

echo "# ==========================================="
echo "# GRAFANA (Optional)"
echo "# ==========================================="
GRAFANA_PASS=$(generate_alphanum 16)
echo "# Grafana admin password: ${GRAFANA_PASS}"
echo "GRAFANA_ADMIN_PASSWORD=${GRAFANA_PASS}"
echo "GRAFANA_OAUTH_CLIENT_ID="
echo "GRAFANA_OAUTH_CLIENT_SECRET="
echo ""

echo "# ==========================================="
echo "# PORTAL MODULE (Optional)"
echo "# ==========================================="
echo "PORTAL_AUTH_SECRET=$(generate_alphanum 32)"
echo "PORTAL_OAUTH_CLIENT_ID="
echo "PORTAL_OAUTH_CLIENT_SECRET="
echo ""

echo "# ==========================================="
echo "# EMAIL CONFIGURATION (Optional)"
echo "# ==========================================="
echo "SMTP_HOST="
echo "SMTP_PORT=587"
echo "SMTP_USERNAME="
echo "SMTP_PASSWORD="
echo "SMTP_FROM=noreply@example.com"
echo ""

echo "# ==========================================="
echo "# ADMIN MODULE (Optional)"
echo "# ==========================================="
echo "SLACK_WEBHOOK_URL="
echo "SLACK_SIGNING_SECRET="
echo "APPROVAL_API_TOKEN=$(generate_alphanum 48)"
echo ""

echo "# ==========================================="
echo "# AI CONFIGURATION"
echo "# ==========================================="
echo "ANTHROPIC_API_KEY=  # Add your Claude API key"
echo "AI_MODEL=claude-sonnet-4-5-20250929"
echo "OPENAI_API_KEY="
echo "AI_RATE_LIMIT_PER_MINUTE=100"
echo "AI_MAX_TOKENS_PER_REQUEST=4096"
echo "N8N_API_KEY=  # Generate in n8n Settings > API"
echo ""

echo "# ==========================================="
echo "# MCP CONFIGURATION"
echo "# ==========================================="
echo "# OpenBao tokens are generated by init-openbao.sh — see above"

echo ""
echo "# ==========================================="
echo "# IMPORTANT: Update these values before deployment:"
echo "# - DOMAIN"
echo "# - ACME_EMAIL"
echo "# - ANTHROPIC_API_KEY"
echo "# - SMTP settings (if email needed)"
echo "# ==========================================="
